development:
  PARSE_APP_ID: "jjQlIo5A3HWAMRMCkH8SnOfimVfCi6QlOV9ZNO2T"
  PARSE_JAVASCRIPT_KEY: "EK0eXjOx2Ugs26mIUgCzQOMoLBlYbc5Lba9Q6Zba"
production:
  PARSE_APP_ID: "5pYOx25qvyg4IVXyu128IuRlbnJtwLgwCTsHXCpO"
  PARSE_JAVASCRIPT_KEY: "4DpFKlPOHapo9LJ89UcMMQCSnQQ3uD1ZJRwMZrZL"
